name: easymove_merchant
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  getwidget: ^3.0.1
  http: ^0.13.5
  image: ^4.0.15
  dio: ^4.0.6
  flutter_google_places: ^0.3.0
  google_maps_webservice: ^0.0.20-nullsafety.2
  uuid: ^3.0.7
  autocomplete_textfield: ^2.0.1
  shared_preferences: ^2.1.0
  firebase_core: ^2.10.0
  firebase_messaging: ^14.4.1
  flutter_local_notifications: ^14.0.0+1
  flutter_app_badger: ^1.5.0
  intl: ^0.18.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/images/

